# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a736e7d9323699731441ae8e413961336e57b4c5f9828ab0c2df0304edfb48a0eb97d88cecaebb0a08a1c93e849093a28752d08a159962124c5544d5707e4d0f

test:
  secret_key_base: ca2da56fa09a8b3bea588e94edcccb8af23320459be39c9ef6296e6109544eb055926415a72b0e263ca269f3049212d9d4d84603836d0d14d1d75bdce50eb009

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
